### ISSUE TITLE
无法使用unique验证

### ISSUE THREAD

**Issue by lqllife** [webman-tech/laravel-validation#1]
```
{
  "timestamp": "2022-10-18 09:57:40",
  "error_message": "Presence verifier has not been set.",
  "error_trace": [
      "#0 /app/vendor/illuminate/validation/Concerns/ValidatesAttributes.php(854): Illuminate\\Validation\\Validator->getPresenceVerifier()",
      "#1 /app/vendor/illuminate/validation/Validator.php(611): Illuminate\\Validation\\Validator->validateUnique()",
      "#2 /app/vendor/illuminate/validation/Validator.php(417): Illuminate\\Validation\\Validator->validateAttribute()",
      "#3 /app/vendor/illuminate/validation/Validator.php(448): Illuminate\\Validation\\Validator->passes()",
      "#4 /app/app/functions.php(114): Illuminate\\Validation\\Validator->fails()",
      "#5 /app/app/controller/admin/Admin.php(54): param_validator()",
      "#6 /app/vendor/workerman/webman-framework/src/App.php(278): app\\controller\\admin\\Admin->store()",
      "#7 /app/vendor/workerman/webman-framework/src/App.php(304): Webman\\App::Webman\\{closure}()",
      "#8 /app/app/middleware/AdminAuth.php(30): Webman\\App::Webman\\{closure}()",
      "#9 /app/vendor/workerman/webman-framework/src/App.php(299): app\\middleware\\AdminAuth->process()",
      "#10 /app/app/middleware/CheckSign.php(22): Webman\\App::Webman\\{closure}()",
      "#11 /app/vendor/workerman/webman-framework/src/App.php(299): app\\middleware\\CheckSign->process()",
      "#12 /app/app/middleware/AccessControl.php(14): Webman\\App::Webman\\{closure}()",
      "#13 /app/vendor/workerman/webman-framework/src/App.php(299): app\\middleware\\AccessControl->process()",
      "#14 /app/vendor/workerman/webman-framework/src/App.php(515): Webman\\App::Webman\\{closure}()",
      "#15 /app/vendor/workerman/webman-framework/src/App.php(128): Webman\\App::findRoute()",
      "#16 /app/vendor/workerman/workerman/Connection/TcpConnection.php(638): Webman\\App->onMessage()",
      "#17 /app/vendor/workerman/workerman/Events/Select.php(311): Workerman\\Connection\\TcpConnection->baseRead()",
      "#18 /app/vendor/workerman/workerman/Worker.php(2457): Workerman\\Events\\Select->loop()",
      "#19 /app/vendor/workerman/workerman/Worker.php(1568): Workerman\\Worker->run()",
      "#20 /app/vendor/workerman/workerman/Worker.php(1410): Workerman\\Worker::forkOneWorkerForLinux()",
      "#21 /app/vendor/workerman/workerman/Worker.php(1384): Workerman\\Worker::forkWorkersForLinux()",
      "#22 /app/vendor/workerman/workerman/Worker.php(1714): Workerman\\Worker::forkWorkers()",
      "#23 /app/vendor/workerman/workerman/Worker.php(1654): Workerman\\Worker::monitorWorkersForLinux()",
      "#24 /app/vendor/workerman/workerman/Worker.php(561): Workerman\\Worker::monitorWorkers()",
      "#25 /app/vendor/workerman/webman-framework/src/support/App.php(124): Workerman\\Worker::runAll()",
      "#26 /app/start.php(7): support\\App::run()",
      "#27 {main}"
  ],
  "file": "/app/vendor/illuminate/validation/Validator.php",
  "line": 1413
}
```

**Comment by krissss** [comment]
v1.1.0 已支持

[unique 验证器](https://github.com/webman-tech/laravel-validation#unique-%E9%AA%8C%E8%AF%81%E5%99%A8)
